/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus Ariel
 */
public final class ListaEquiUsua extends javax.swing.JFrame {

    private String proyecto;
    private String solicitante;

    /**
     * Creates new form listaEquipos
     */
    public ListaEquiUsua() {
        String cate = null;
        initComponents();
        iniciar2();
        iniciar(cate);
        
    }

    ListaEquiUsua(String[] ides2, String proyecto, String solicitante, boolean usuario) {
        String cate = null;
        initComponents();
        iniciar2();
        iniciar(cate);
        recorre();
        seleccionados(ides2);
        this.proyecto = proyecto;
        this.solicitante = solicitante;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabEquipo = new javax.swing.JTable();
        Categoria = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTA DE EQUIPOS (MODO USUARIO)");

        jButton5.setText("Pagina Principal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Prestar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tabEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Equipo", "Nombre del Equipo", "Accesorios", "Decripción", "Marca", "Equipo Activo/Inactivo", "Seleccionar "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabEquipo);
        if (tabEquipo.getColumnModel().getColumnCount() > 0) {
            tabEquipo.getColumnModel().getColumn(5).setResizable(false);
        }

        Categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cables y Adaptadores", "Computación" }));
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrar Equipo por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jButton6)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                                   
         String ide = null;
         int mnb=0;
         int e = 0;
         for(int i=0; i<tabEquipo.getRowCount();i++)
         {
             if((boolean)tabEquipo.getValueAt(i,7) == true)
                {
                   e++;
                }
         }
         int n = e;
         String[] ides = new String[n];
         if(e>=1){
            for(int i=0; i<tabEquipo.getRowCount();i++)
            {
               if((boolean)tabEquipo.getValueAt(i,7) == true)
                {
                ide  = (String)tabEquipo.getValueAt(i,0);
                ides[mnb] = ide;
                mnb++;                
                }
            }
     nuevoReporte IE= new nuevoReporte(ides,true);
         IE.setVisible(true);
         dispose();
         }else 
         {
            if(ide == null) 
                     {
                        JOptionPane.showMessageDialog(rootPane, "Selecciona el o los equipo(s) que desees o prestar");
                     }
             }
         /*for(int i=0; i<ides.length; i++)
         {
             System.out.print(ides[i]);
             System.out.println("\n Lista equipos");
         }*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        entrar pp= new entrar();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
        Limpiar(tabEquipo);
        Object cat = Categoria.getSelectedItem();
        String cate = String.valueOf(cat);
        iniciar(cate);
        recorre();
        //tabEquipo.setModel(new DefaultTableModel());
        
    }//GEN-LAST:event_CategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEquiUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEquiUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEquiUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEquiUsua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListaEquiUsua().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Categoria;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabEquipo;
    // End of variables declaration//GEN-END:variables

    
    public void iniciar(String cate)
    {
        conectar cc = new conectar(); // Llamar al objeto conectar 
        Connection con = cc.conexion();//creamos la variable conexion con el metodo conexion 
        DefaultTableModel Modelo = (DefaultTableModel) tabEquipo.getModel();

        try{    
        String sql = "select idEquipo, nomEquipo, Categoria, accesorios, descEquipo,"
                + "marcaEquipo, equipoActivo from equipo where Categoria = '" +cate+ "' order by IdEquipo;";
            try (CallableStatement cmd = con.prepareCall(sql)) {
                ResultSet rs = cmd.executeQuery();
                while (rs.next()) {
                    Object[] datos = new Object [7];
                    for (int i=0; i<=6; i++){
                        datos [i] = rs.getString(i+1);
                        //System.out.println(datos [i]);
                        //System.out.println(rs);
                    }
                    Modelo.addRow(datos);
                }   }
        con.close();
    }catch(Exception ex){
        System.out.println(ex.getMessage());
    }      
    }
    public void iniciar2()
    {
        conectar cc = new conectar(); // Llamar al objeto conectar 
        Connection con = cc.conexion();//creamos la variable conexion con el metodo conexion 
        DefaultTableModel Modelo = (DefaultTableModel) tabEquipo.getModel();

        try{    
        String sql = "SELECT idEquipo, nomEquipo,Categoria, accesorios, descEquipo,"
                + "marcaEquipo, equipoActivo FROM equipo WHERE Categoria='Cables y Adaptadores' order by IdEquipo;";
            try (CallableStatement cmd = con.prepareCall(sql)) {
                ResultSet rs = cmd.executeQuery();
                while (rs.next()) {
                    Object[] datos = new Object [7];
                    for (int i=0; i<=6; i++){
                        datos [i] = rs.getString(i+1);
                        //System.out.println(datos [i]);
                        //System.out.println(rs);
                    }
                    Modelo.addRow(datos);
                }   }
        con.close();
    }catch(Exception ex){
        System.out.println(ex.getMessage());
    }
        //recorre();
    }
  public void recorre()
  {
      for(int i=0; i<tabEquipo.getRowCount();i++)
      {
          tabEquipo.setValueAt(false, i, 6);         
      }
  }
  private void Limpiar(JTable tabEquipoJTable) {
        while (tabEquipo.getRowCount()>0){
            ((DefaultTableModel) tabEquipo.getModel()).removeRow(0);
        }
    }  
  public void seleccionados(String[] ides2)
  {
      System.out.println("Entra a Seleccionados");
      for(int i=0; i<ides2.length; i++)
      {
          System.out.println("Aqui pasa por los ides2");
          System.out.println(ides2[i]);
          for(int p=0; p<= tabEquipo.getRowCount()-1; p++){
              System.out.println("Aqui pasa por la tabla");
              System.out.println( ides2[i] + " =? " +tabEquipo.getValueAt(p, 0));
              if(ides2[i].compareTo(tabEquipo.getValueAt(p, 0).toString()) == 0){
                System.out.println("Se supone que los marca");
                tabEquipo.setValueAt(true, p, 7);
          
              }
          }
      }
  }
}

/*
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
           if (response == JOptionPane.NO_OPTION) {
             System.out.println("No button clicked");
           } else if (response == JOptionPane.YES_OPTION) {
             System.out.println("Yes button clicked");
           } else if (response == JOptionPane.CLOSED_OPTION) {
             System.out.println("JOptionPane closed");
           }
*/